
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 9 * * *"


jobs:

  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Terraform
      run: |
        wget https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
        unzip terraform_1.3.7_linux_amd64.zip
        sudo mv ./terraform /usr/local/bin
        rm -rf terraform_1.3.7_linux_amd64.zip

    - name: Run Terraform Init
      run: terraform init -backend=false

    - name: Run Terraform Validate
      run: terraform validate .
